baseURL = "https://djosephsen.github.io//"
languageCode = "en-us"
title = "One Dave's Blog"
theme = "m10c"
copystart = "2020"

[params]
author = "Dave Josephsen"
authorformal = "David J. Josephsen"
description = "The astonishing thoughtfacts of an idiomaniacal mindshepherd"
avatar = "avatar.jpg"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

[[menu.main]]
identifier = "rss"
name = "rss"
url = "/index.xml"

[[params.social]]
icon = "rss"
name = "RSS"
url = "http://djosephsen.github.io/index.xml"

[[params.social]]
icon = "mastodon"
name = "Mastodon"
url = "https://hachyderm.io/@djosephsen"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/@DaveJosephsen"

[[params.social]]
icon = "github"
name = "Github"
url = "http://github.com/djosephsen"

[[params.social]]
icon = "linkedin"
name = "Linked-in"
url = "https://www.linkedin.com/in/davejosephsen/"
