baseURL = "https://djosephsen.github.io//"
languageCode = "en-us"
title = "One Dave's Blog"
theme = "m10c"

[params]
    author = "Dave Josephsen"
    description = "The astonishing thoughtfacts of a idiomaniacal mindshepherd"
    avatar = "avatar.jpg"

[[menu.main]]
  identifier = "tags"
  name = "Posts by Tag"
  url = "/tags/"

[[menu.main]]
  identifier = "rss"
  name = "rss"
  url = "/index.xml"

[[params.social]]
  icon = "rss"
  name = "RSS"
  url = "http://djosephsen.github.io/index.xml"

[[params.social]]
  icon = "mastodon"
  name = "Mastodon"
  url = "https://hachyderm.io/@djosephsen"

[[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://hachyderm.io/@DaveJosephsen"

[[params.social]]
  icon = "github"
  name = "Github"
  url = "http://github.com/djosephsen"

[[params.social]]
  icon = "linkein"
  name = "Linked-in"
  url = "https://www.linkedin.com/in/davejosephsen/"

